### ISSUE TITLE
Default clusters can't be removed

### ISSUE THREAD

**Issue by maxime-menard** [EladLeev/kafka-config-metrics#26]
When using the helm chart, those clusters are automatically added, and can't be removed :

```
clusters:
    prod:
      brokers: "kafka01-prod"
      topicfilter: ""
    test:
      brokers: "kafka01-test"
      topicfilter: "^(qa-|test-).*$"
```
One way would be to just comment them in the values.yaml ?

One side note, I didn't see the helm chart published in a chart repo (no index,yaml), how can I add this chart as a dependency in my own helm chart ?

Thanks !
